CREATE TABLE IF NOT EXISTS care_schedule_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  care_plan_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  instruction_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(160) NOT NULL,
  task_kind ENUM('medicine', 'lab_test', 'follow_up', 'care_task', 'other') NOT NULL DEFAULT 'other',
  schedule_date DATE NULL,
  schedule_time TIME NULL,
  display_time VARCHAR(160) NULL,
  recurrence_text VARCHAR(160) NULL,
  grounding ENUM('explicit', 'suggested') NOT NULL,
  requires_confirmation TINYINT(1) NOT NULL DEFAULT 0,
  confirmation_status ENUM('ready', 'needs_confirmation') NOT NULL DEFAULT 'ready',
  reason VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY care_schedule_plan_index (care_plan_id),
  KEY care_schedule_user_index (user_id),
  KEY care_schedule_instruction_index (instruction_id),
  CONSTRAINT care_schedule_plan_fk FOREIGN KEY (care_plan_id) REFERENCES care_plans(id) ON DELETE CASCADE,
  CONSTRAINT care_schedule_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT care_schedule_instruction_fk FOREIGN KEY (instruction_id) REFERENCES extracted_instructions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
