CREATE TABLE IF NOT EXISTS care_reality_question_sets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  care_plan_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  context_hash CHAR(64) NOT NULL,
  version INT UNSIGNED NOT NULL,
  generator_version VARCHAR(60) NOT NULL,
  status ENUM('active', 'retired') NOT NULL DEFAULT 'active',
  question_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY care_reality_question_set_version_unique (care_plan_id, user_id, version),
  KEY care_reality_question_set_active_idx (care_plan_id, user_id, status, created_at),
  KEY care_reality_question_set_context_idx (care_plan_id, user_id, context_hash),
  CONSTRAINT care_reality_question_set_plan_fk FOREIGN KEY (care_plan_id) REFERENCES care_plans (id) ON DELETE CASCADE,
  CONSTRAINT care_reality_question_set_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS care_reality_questions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  question_set_id BIGINT UNSIGNED NOT NULL,
  care_plan_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  question_key VARCHAR(80) NOT NULL,
  ordinal SMALLINT UNSIGNED NOT NULL,
  intent VARCHAR(60) NOT NULL,
  category VARCHAR(80) NOT NULL,
  question_text VARCHAR(500) NOT NULL,
  response_profile VARCHAR(60) NOT NULL,
  target_task_ids_json LONGTEXT NOT NULL,
  period VARCHAR(20) NOT NULL DEFAULT 'any',
  reason_for_asking VARCHAR(500) NOT NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'ai_generated',
  status ENUM('active', 'retired') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY care_reality_question_set_key_unique (question_set_id, question_key),
  KEY care_reality_question_plan_key_idx (care_plan_id, user_id, question_key),
  KEY care_reality_question_status_idx (question_set_id, status, ordinal),
  CONSTRAINT care_reality_question_set_fk FOREIGN KEY (question_set_id) REFERENCES care_reality_question_sets (id) ON DELETE CASCADE,
  CONSTRAINT care_reality_question_plan_fk FOREIGN KEY (care_plan_id) REFERENCES care_plans (id) ON DELETE CASCADE,
  CONSTRAINT care_reality_question_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
